spring.config.import=optional:classpath:application-secrets.properties

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.iyjaqssponxgvurchioj
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=604800000

naver.client-id=${NAVER_CLIENT_ID}
naver.client-secret=${NAVER_CLIENT_SECRET}