spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.iyjaqssponxgvurchioj
spring.datasource.password=*F7zL&iL#etjv3e

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

jwt.secret=kFL5yOODkZZTRtRknMCC2gOrR4Pie8t1zALkt/s51dM=
jwt.expiration-ms=604800000